name: Deploy Frontend with Sentry Sourcemap Upload

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare Yarn 4.9.2
        run: corepack prepare yarn@4.9.2 --activate

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Get commit SHA
        id: get-sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Install Sentry CLI
        run: yarn global add @sentry/cli

      - name: Create Sentry release & upload sourcemaps
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        run: |
          export SENTRY_RELEASE=${{ steps.get-sha.outputs.sha }}
          sentry-cli releases new $SENTRY_RELEASE
          sentry-cli releases files $SENTRY_RELEASE upload-sourcemaps dist/ --url-prefix '~/assets' --validate
          sentry-cli releases finalize $SENTRY_RELEASE

      - name: Deploy
        run: ./your-deploy-script.sh 